### ISSUE TITLE
Can't add keybindings for ctrl and special characters (left, right, ...) wont work

### ISSUE THREAD

**Issue by froggydood** [kammerdienerb/yed#20]
When I try and use ctrl-left or any ctrl cursor key it only comes up with, for left ctrl-l, for right, ctrl-r and so on.

Also my ctrl-tab keybind only inserts a tab and doesn't execute a command.

Any help would be greatly appreciated as I do the love the editor itself.

**Comment by kammerdienerb** [comment]
Unfortunately, none of this is possible in a terminal-based editor (which `yed` is). The terminal simply does not send that kind of information to the programs running within it, so `yed` can't possible know what modifiers you have pressed. For `ctrl`, only certain keys have a corresponding ASCII byte that isn't already taken up by a special control character. Here's a decent explanation of why this doesn't work in `vim`: https://vi.stackexchange.com/questions/19358/cannot-map-ctrl-number-except-6-or
